config/routes.rb
# ルーティング構成を変更した場合は
# bundle exec rake js:routes
# を実行して app/assets/javascripts/routes.js を更新してください。
#
Rails.application.routes.draw do

  resources :events
  resources :carees do
    member do
      get "locations"
    end
  end

  resources :mqtturis, only:[:index], path:'mqtturi'
  root to: 'welcome#index'
end

app/models/caree.rb
# == Schema Information
#
# Table name: carees
#
#  id         :integer          not null, primary key
#  name       :string(192)      not null
#  icon       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  age        :integer
#
# Indexes
#
#  index_carees_on_name  (name)
#

class Caree < ActiveRecord::Base
  has_many :events
  has_one :last_event, -> { order(id: :desc) }, class_name: 'Event'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id             :integer          not null, primary key
#  caree_id       :integer
#  event          :string(36)       not null
#  heartrate      :float
#  latitude       :float
#  longitude      :float
#  altitude       :float
#  acceleration_x :float
#  acceleration_y :float
#  acceleration_z :float
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_events_on_event  (event)
#

class Event < ActiveRecord::Base
  belongs_to :caree

  scope :valid_location, -> { where.not(latitude: nil).where.not(longitude: nil) }

  class << self
    def to_google_map_polyline_format
      all.pluck(:latitude, :longitude).map { |lat, lng| { lat: lat, lng: lng } }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carees_controller.rb
class CareesController < ApplicationController
  before_action :set_caree, only: [:show, :edit, :update, :destroy, :locations]

  # GET /carees/1/locations
  def locations
    @locations = @caree.events.valid_location.order(id: :desc).limit(100).to_google_map_polyline_format
    respond_to do |format|
      format.html { render :show_locations }
      format.json { render :show_locations }
    end
  end

  # GET /carees
  # GET /carees.json
  def index
    @carees = Caree.includes(:last_event).all
  end

  # GET /carees/1
  # GET /carees/1.json
  def show
  end

  # GET /carees/new
  def new
    @caree = Caree.new
  end

  # GET /carees/1/edit
  def edit
  end

  # POST /carees
  # POST /carees.json
  def create
    @caree = Caree.new(caree_params)

    respond_to do |format|
      if @caree.save
        format.html { redirect_to @caree, notice: 'Caree was successfully created.' }
        format.json { render :show, status: :created, location: @caree }
      else
        format.html { render :new }
        format.json { render json: @caree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carees/1
  # PATCH/PUT /carees/1.json
  def update
    respond_to do |format|
      if @caree.update(caree_params)
        format.html { redirect_to @caree, notice: 'Caree was successfully updated.' }
        format.json { render :show, status: :ok, location: @caree }
      else
        format.html { render :edit }
        format.json { render json: @caree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carees/1
  # DELETE /carees/1.json
  def destroy
    @caree.destroy
    respond_to do |format|
      format.html { redirect_to carees_url, notice: 'Caree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_caree
      @caree = Caree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def caree_params
      params.fetch(:caree, {}).permit(:name, :age, :icon)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if params[:all]
      @events = Event.order(id: :desc).all
    else
      @events = Event.order(id: :desc).limit(100)
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.fetch(:event, {}).permit(:event, :caree_id)
    end
end

app/controllers/mqtturis_controller.rb
class MqtturisController < ApplicationController
  # GET /mqtturis.json
  def index
    uri = SigV4UtilsForAwsIoT.createEndpoint(ENV['MQTT_URI'] || 'a284fmjqennl6d.iot.ap-northeast-1.amazonaws.com')
    render text: {uri:uri}.to_json
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carees_helper.rb
module CareesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/mqtturis_helper.rb
module MqtturisHelper
end

app/views/application/_sidebar.html.erb
<ul class="status">
</ul>

app/views/carees/_form.html.erb
<%= form_for(@caree) do |f| %>
  <% if @caree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@caree.errors.count, "error") %> prohibited this caree from being saved:</h2>

      <ul>
      <% @caree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tbody>
      <tr>
        <td>Name</td>
        <td><%= text_field :caree, :name, size:40, maxlength:192 %></td>
      </tr>
      <tr>
        <td>Icon (URI)</td>
        <td><%= text_field :caree, :icon, size:100, maxlength:4096 %></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carees/edit.html.erb
<h1>Editing Caree</h1>

<%= render 'form' %>

<%= link_to 'Show', @caree %> |
<%= link_to 'Back', carees_path %>

app/views/carees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Carees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Event count</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carees.each do |caree| %>
      <tr>
        <td><%= caree.name %></td>
        <td><%= caree.age %></td>
        <td><%= caree.event_ids.size %></td>
        <td><a href="<%= caree.icon %>">CLICK</a></td>
        <td><%= link_to 'Show', caree %></td>
        <td><%= link_to 'Edit', edit_caree_path(caree) %></td>
        <td><%= link_to 'Destroy', caree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Caree', new_caree_path %>

app/views/carees/new.html.erb
<h1>New Caree</h1>

<%= render 'form' %>

<%= link_to 'Back', carees_path %>

app/views/carees/show.html.erb
<p id="notice"><%= notice %></p>
<table>
  <tbody>
    <tr>
      <td>Name</td>
      <td><%= @caree.name %></td>
    </tr>
    <tr>
      <td>Age</td>
      <td><%= @caree.age %></td>
    </tr>
    <tr>
      <td>Icon (URI)</td>
      <td><%= @caree.icon %></td>
    </tr>
    <tr>
      <td>Event count</td>
      <td><%= @caree.event_ids.size %></td>
    </tr>
    <tr>
      <td>Last event</td>
      <td><%= if @caree.last_event then @caree.last_event.id else "-" end  %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_caree_path(@caree) %> |
<%= link_to 'Back', carees_path %>

app/views/carees/show_locations.html.erb
<p id="notice"><%= notice %></p>

<div><img src="<%= @caree.icon %>" /><span><%= @caree.name %> (<%= @caree.id %>)</span></div>

<table>
  <thead>
    <tr>
      <th>Locations (<%= @locations.count %>)</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td>
          <%= location[:lat] %>, <%= location[:lng] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_caree_path(@caree) %> |
<%= link_to 'Back', carees_path %>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tbody>
      <tr>
        <td>Event</td>
        <td><%= text_field :event, :event, size:40, maxlength:36 %></td>
      </tr>
      <tr>
        <td>User ID</td>
        <td><%= text_field :event, :caree_id, size:40, maxlength:10 %></td>
      </tr>
    </tbody>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Event</th>
      <th>Heartrate</th>
      <th>Location</th>
      <th>Acceleration</th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= caree = Caree.find(event.caree_id); "#{caree.name} (#{caree.id})" %></td>
        <td><%= event.event %></td>
        <td><%= event.heartrate %></td>
        <td>
          <% if event.latitude and event.longitude %>
            <%= event.latitude %>,<%= event.longitude %>
          <% end %>
          <% if event.altitude %>
            <%= event.altitude %>
          <% end %>
        </td>
        <td>
          <% if event.acceleration_x and event.acceleration_y and event.acceleration_z %>
            <%= event.acceleration_x %>, <%= event.acceleration_y %>, <%= event.acceleration_z %>
          <% end %>
        </td>
        <!--
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : t('app_title') %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>

    <script src="/mqttws31.js" type="text/javascript"></script>
    <script src="//maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
  </head>
  <body class="<%= [controller_name, action_name].join(' ') %>" >

    <div id="wrap">

      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">

          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <!--
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            -->
            <%= link_to t('app_title'), root_path, class: 'navbar-brand' %>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <!--
          <div class="navbar-collapse collapse navbar-responsive-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to "Link1", '#' %></li>
              <li><%= link_to "Link2", '#' %></li>
              <li><%= link_to "Link3", '#' %></li>
            </ul>
          </div>
          -->
          <!-- /.navbar-collapse -->
        </div>
      </nav>

      <div class="container main">

        <div class="row">
          <div class="col-md-8">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="col-md-4">
            <%= render partial: 'sidebar' %>
          </div><!--/span-->

          <%= image_tag 'valinor-lord-of-the-rings.jpg' %>

        </div><!--/row-->
      </div> <!-- /container -->
    </div>

    <footer>
      <div class="container">
        <div class="row">
          <address class="text-center">
            &copy; <%= t('copyright') %> 2016
          </address>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/welcome/index.html.erb
<div id="googleMap">
  <div id="map_canvas"></div>
  <div>MQTT Status<code id="status">---</code></div>
  <div>Publish example:<code>{"caree_id":1,"event":"MOVED", "location":{"lat":35.515132, "lon":134.1696503}}</code></div>
  <div id="careeDialog" title="--name--">
    <div class="event"></div>
    <div class="location"></div>
    <div class="heartrate"></div>
  </div>
</div>